### The current work is devoted to comparison of metaphorical usages of adjectives in collocations on the example of British English and Castillian Spanish. We analyze the first 100 popular collocations with an adjective with the meaning "round" in both corpora. To each of them we have given a label "1" or "0" depending on the fact wheter the adjective with the meaning "round" was used in its indirect meaning or not. So metaphorical and non-metaphorical collocations got the labels "1" and "0" respectively.
library(ggplot2)

## 1.First let us consider metaphorical usage of an adjective "round" in English and "redondo" in Spanish collocation
# set working directory  
setwd ("C:/Users/Настя/Desktop/Учёба/Databases")

# read the file with english collocations 
eng <- read.csv("british.csv")

# read the file with spanish collocations
esp <- read.csv ("spanish.csv")

# read files in the directory to R
myfiles  <- lapply(list.files(), read.delim)

# merge files into one dataframe 
result_df <- rbind(eng, esp)

# create labels 
metaphor <- c("English", "Spanish")
result_df$label <- rep(metaphor, sapply(myfiles, nrow))

# draw the plot 
counts <- table(result_df$metaphor, result_df$label)
barplot(counts, main= "Metaphorical usage of the adjective with the meaning round",
        xlab="Languages", col= c("green","orange"),
        legend = c("direct", "metaphor"))
        
## 2. Here we are going to observe frequencies of metaphorical and direct usages in English and Spanish
#  2.1 We shall start with english collocations 
eng <- read.csv("british.csv")

# 3 dataframes to visualize: the whole sample, metaphorical collocations and collocations with the adjective "redondo" in its direct meaning
english <- data.frame(eng[ , -3], "metaphor" = as.logical(eng$metaphor), stringsAsFactors = FALSE)
met_eng <- data.frame(filter(english, metaphor == TRUE))
dir_eng <- data.frame(filter(english, metaphor == FALSE))

# draw histograms with a normal curve 
  a <- english$frequency
  b <- met_eng$frequency
  c <- dir_eng$frequency
grid <- matrix(c(1,1,2,3), nrow = 2, ncol = 2, byrow = TRUE)  
layout(grid)
  
  hist(a,breaks=10,  col="blue", xlab="Frequency in corpus",
       main="Collocations with the adjective round") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="red", lwd=2)
  
  hist(b,breaks=10,  col="blue", xlab="Frequency in corpus",
       main="Metaphorical collocations with the adjective round") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="red", lwd=2)
  
  hist(c,breaks=10,  col="blue", xlab="Frequency in corpus",
       main="Collocations with the adjective round in direct meaning") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="red", lwd=2)
    
# Seems that we have managed to create 3 histograms with the frequencies of collocations with the adjective "round" in different roles
# 2.2 Now it is time to repeat the excercise on the base of Spanish language
  
esp <- read.csv ("spanish.csv")

# again forming 3 dataframes to work at
spanish <- data.frame(esp[ ,-3], "metaphor" = as.logical(esp$metaphor), stringsAsFactors = FALSE)
met_esp <- data.frame(filter(spanish, metaphor == TRUE))
dir_esp <- data.frame(filter(spanish, metaphor == FALSE))

# Did you miss the histograms? Here they are! 
  x <- met_esp$frequency
  y <- spanish$frequency
  z <- dir_esp$frequency

grid <- matrix(c(1,1,2,3), nrow = 2, ncol = 2, byrow = TRUE)  
layout(grid)
   
   hist(y,breaks=10,  col="red", xlab="Frequency in corpus",
         main="Collocations with the adjective redondo") 
      xfit<-seq(min(x),max(x),length=40) 
      yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
      yfit <- yfit*diff(h$mids[1:2])*length(x) 
      lines(xfit, yfit, col="blue", lwd=2)
      
    hist(x, breaks=10,  col="red", xlab="Frequency in corpus",
           main="Metaphorical collocations with the adjective redondo") 
      xfit<-seq(min(x),max(x),length=40) 
      yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
      yfit <- yfit*diff(h$mids[1:2])*length(x) 
      lines(xfit, yfit, col="blue", lwd=2)
      
    hist(z,breaks=10,  col="red", xlab="Frequency in corpus",
         main="Collocations with the adjective redondo in direct meaning") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="blue", lwd=2)
    
# 3.3 Now we are eager to compare metaphorical and direct usages of adjectives with the meaning "round" in both languages
  grid <- matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE)  
  layout(grid)
    hist(b,breaks=10,  col="blue", xlab="Frequency in corpus",
       main="Metaphorical collocations with the adjective round") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="red", lwd=2)
    
    hist(x, breaks=10,  col="red", xlab="Frequency in corpus",
         main="Metaphorical collocations with the adjective redondo") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="blue", lwd=2)
    
    hist(c,breaks=10,  col="blue", xlab="Frequency in corpus",
         main="Collocations with the adjective round in direct meaning") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="red", lwd=2)
    
    hist(z,breaks=10,  col="red", xlab="Frequency in corpus",
         main="Collocations with the adjective redondo in direct meaning") 
    xfit<-seq(min(x),max(x),length=40) 
    yfit<-dnorm(xfit,mean=mean(x),sd=sd(x)) 
    yfit <- yfit*diff(h$mids[1:2])*length(x) 
    lines(xfit, yfit, col="blue", lwd=2)

    